runtime: python39  # Esto puede variar según la versión de Python que estés utilizando
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

# Configuración adicional (si es necesario)
env_variables:
  MY_ENV_VARIABLE: "valor"

# Configuración de recursos (si es necesario)
# automatic_scaling, resources, etc.
